/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nestoralberto.view;

import com.nestoralberto.controller.NotaController;
import com.nestoralberto.model.Nota;

/**
 *
 * @author albertobq
 */
public class FrmNota extends javax.swing.JFrame {

    /**
     * Creates new form FrmNota
     */
//    NotaController controller = new NotaController();
    
    public FrmNota() {
        initComponents();
//        init();
    }
    
    private void init() {
//        controller.listarNotas(listNota);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPrincipal = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNota = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(330, 420));

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        btnEliminar.setText("Bievenido");
        jPanel1.add(btnEliminar);

        panelPrincipal.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(listNota);

        panelPrincipal.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(312, 160));
        jPanel2.setLayout(null);

        jLabel1.setText("Titulo");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 70, 14);
        jPanel2.add(textTitulo);
        textTitulo.setBounds(90, 10, 210, 20);

        jLabel2.setText("Descripcion");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 40, 70, 14);

        textDescripcion.setColumns(20);
        textDescripcion.setLineWrap(true);
        textDescripcion.setRows(5);
        jScrollPane2.setViewportView(textDescripcion);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(90, 40, 210, 70);

        btnAgregar.setText("Agregar");
        jPanel2.add(btnAgregar);
        btnAgregar.setBounds(200, 120, 100, 30);

        labelMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelMensaje.setForeground(new java.awt.Color(255, 0, 0));
        labelMensaje.setText("labelMensaje");
        labelMensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(labelMensaje);
        labelMensaje.setBounds(10, 120, 170, 30);

        panelPrincipal.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        scrollPrincipal.setViewportView(panelPrincipal);

        getContentPane().add(scrollPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labelMensaje;
    public javax.swing.JList<Nota> listNota;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollPrincipal;
    public javax.swing.JTextArea textDescripcion;
    public javax.swing.JTextField textTitulo;
    // End of variables declaration//GEN-END:variables
}
